
include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - avoid_void_async

analyzer:
#   exclude:
#     - path/to/excluded/files/**
