# Lints set up with some guidance from here:
# https://rydmike.com/blog_flutter_linting.html

include: tool/misc/all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore

linter:
  rules:
    always_specify_types: false
    avoid_annotating_with_dynamic: false
    avoid_classes_with_only_static_members: false
    avoid_js_rounded_ints: false # see https://github.com/intel/rohd/pull/213
    dangling_library_doc_comments: false # TEMPORARY: https://github.com/intel/rohd/issues/264
    prefer_double_quotes: false
    prefer_final_parameters: false
    prefer_relative_imports: false
    require_trailing_commas: false
    sort_constructors_first: false
    unnecessary_final: false
    unnecessary_statements: false
