name: rohd_code
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0-210.1.beta

# Add regular dependencies here.
dependencies:
  rohd: ^0.5.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
