name: Feature Request
description: Suggest an idea for this project.
labels: enhancement

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to suggest a new feature!

  - type: textarea
    attributes:
      label: Motivation
      description: >
        Is your feature request related to a problem?
        Please provide a clear and concise description of what the problem is.
      placeholder: For example, "I'm always frustrated when ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Desired solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: >
        A clear and concise description of any alternative solutions
        or features you've considered.

  - type: textarea
    attributes:
      label: Additional details
      description: Add any other context or screenshots about the feature request here.
