name: rohd_waveform
description: "Waveform data models and APIs for wave viewers - ModuleStructure, SignalWaveform, and waveform primitives."
homepage: https://intel.github.io/rohd-website/
repository: https://github.com/intel/rohd/tree/main/packages/rohd_waveform
version: 0.1.0
issue_tracker: https://github.com/intel/rohd/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  equatable: ^2.0.5
  rohd_hierarchy: ^0.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.17.3
