name: rohd_devtools_extension
description: "DevTool extension on ROHD."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
 sdk: ^3.6.0
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rohd:
    path: ../../rohd
  # devtools_shared: ^6.0.0
  devtools_extensions: ^0.5.0
  devtools_app_shared: ^0.5.0
  vm_service: ^14.3.1
  flutter_simple_treeview: ^3.0.2
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  web: ^1.0.0
  export_png:
    path: packages/export_png
  help_api:
    path: packages/help_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mocktail: ^1.0.2
  bloc_lint: ^0.3.7
  
flutter:
  uses-material-design: true
  assets:
    - assets/help/

