// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: BSD-3-Clause
//
// system_verilog_service.dart
// Service wrapper for SystemVerilog synthesis.
//
// 2026 April 25
// Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

import 'dart:convert';
import 'dart:io';

import 'package:rohd/rohd.dart';
import 'package:rohd/src/utilities/config.dart';
import 'package:rohd/src/utilities/timestamper.dart';

/// A service that wraps SystemVerilog synthesis of a [Module] hierarchy.
///
/// Provides access to the generated SV file contents and per-module
/// synthesis results, and optionally registers with [ModuleServices]
/// for DevTools inspection.
///
/// Example:
/// ```dart
/// final dut = MyModule(...);
/// await dut.build();
/// final sv = SystemVerilogService(
///   dut,
///   outputDirectory: 'build',
///   multiFile: true,
/// );
///
/// // Write individual .sv files:
/// sv.writeOutputs();
///
/// // Or get the concatenated output (like generateSynth):
/// print(sv.output);
/// ```
class SystemVerilogService extends CodeGenService {
  /// The separator inserted between module definitions in the
  /// concatenated single-file output from [allContents].
  ///
  /// Matches the historical single-file synthesis output format.
  static const moduleSeparator = '\n\n////////////////////\n\n';

  /// Whether the artifact layout emits one `.sv` file per module definition
  /// (`true`) or a single concatenated file (`false`).
  final bool multiFile;

  /// Whether generated SV files include the ROHD generation header.
  ///
  /// Defaults to `true` for single-file output and `false` for multi-file
  /// output, preserving the historical layout. Set explicitly to select any
  /// combination of header and file layout.
  final bool includeHeader;

  /// Configuration controlling generated SystemVerilog.
  final SystemVerilogSynthesizerConfiguration configuration;

  /// The underlying [SynthBuilder] that drove synthesis.
  late final SynthBuilder synthBuilder;

  /// The generated file contents (one per unique module definition).
  late final List<SynthFileContents> fileContents;

  /// Creates a [SystemVerilogService] for [module].
  ///
  /// [module] must already be built.
  ///
  /// [outputDirectory] defaults to the current directory and [outputBaseName]
  /// defaults to [Module.definitionName]. [includeHeader] defaults to
  /// `!multiFile` to preserve the historical layout.
  SystemVerilogService(
    Module module, {
    super.outputDirectory,
    super.outputBaseName,
    this.multiFile = false,
    bool? includeHeader,
    this.configuration = const SystemVerilogSynthesizerConfiguration(),
  })  : includeHeader = includeHeader ?? !multiFile,
        super(module) {
    if (!module.hasBuilt) {
      throw Exception(
          'Module must be built before creating SystemVerilogService. '
          'Call build() first.');
    }

    synthBuilder = SynthBuilder(
        module, SystemVerilogSynthesizer(configuration: configuration));
    fileContents = synthBuilder.getSynthFileContents();
  }

  /// All [SynthesisResult]s produced by synthesis.
  Set<SynthesisResult> get synthesisResults => synthBuilder.synthesisResults;

  /// Returns the concatenated SystemVerilog module definitions as a single
  /// string, without the generation header.
  ///
  /// For the full output with header (matching `Module.generateSynth()`),
  /// use [output].
  String get allContents =>
      fileContents.map((fc) => fc.contents).join(moduleSeparator);

  /// The ROHD generation header prepended to single-file output.
  String get synthHeader => '''
/**
 * Generated by ROHD - www.github.com/intel/rohd
 * Generation time: ${Timestamper.stamp()}
 * ROHD Version: ${Config.version}
 */

''';

  /// The generation header included in each emitted SV file, when enabled.
  ///
  /// Cached so output and emitted files always use the same timestamp.
  late final String header = includeHeader ? synthHeader : '';

  /// Returns the full single-file SystemVerilog output with header,
  /// identical to `Module.generateSynth()`.
  ///
  /// Computed once and cached so the timestamped header is stable for the
  /// lifetime of this service.
  @override
  late final String output = header + allContents;

  /// Returns SV output for a generated module [instanceTypeName], or `null`
  /// when that instance type was not generated.
  ///
  /// The instance type name is [SynthesisResult.instanceTypeName], the
  /// uniquified definition name used in the generated SV.
  String? instanceTypeOutput(String instanceTypeName) {
    for (final fc in fileContents) {
      if (fc.name == instanceTypeName) {
        return fc.contents;
      }
    }
    return null;
  }

  /// Returns a map from generated module instance type name to its SV contents.
  ///
  /// Keys are [SynthesisResult.instanceTypeName] (the uniquified definition
  /// name used in the generated SV).
  @Deprecated('Use instanceTypeOutput(instanceTypeName) for lookup or '
      'fileContents for iteration instead.')
  Map<String, String> get contentsByName => {
        for (final fc in fileContents) fc.name: fc.contents,
      };

  /// The artifacts generated by this service.
  ///
  /// Single-file output is named `<outputBaseName>.sv`. Split output retains
  /// the generated definition names so module references remain obvious.
  @override
  Iterable<ModuleServiceArtifact> get artifacts => multiFile
      ? [
          for (final fc in fileContents)
            ModuleServiceArtifact(
              fileName: '${fc.name}.sv',
              mediaType: 'text/x-systemverilog',
              openRead: () => Stream.value(utf8.encode(header + fc.contents)),
            ),
        ]
      : [
          ModuleServiceArtifact(
            fileName: '$outputBaseName.sv',
            mediaType: 'text/x-systemverilog',
            openRead: () => Stream.value(utf8.encode(output)),
          ),
        ];

  /// Writes this service's artifacts to [outputDirectory].
  void writeOutputs() {
    final directory = Directory(outputDirectory)..createSync(recursive: true);
    if (multiFile) {
      for (final fc in fileContents) {
        File('${directory.path}/${fc.name}.sv')
            .writeAsStringSync(header + fc.contents);
      }
    } else {
      File('${directory.path}/$outputBaseName.sv').writeAsStringSync(output);
    }
  }

  /// Writes the single-file output to an exact legacy [outputPath].
  ///
  /// This preserves the legacy convenience API's arbitrary filename behavior.
  /// New service code should use [outputDirectory], [outputBaseName], and
  /// [writeOutputs].
  void writeLegacyOutputPath(String outputPath) {
    if (multiFile) {
      throw StateError(
        'writeLegacyOutputPath is only valid for single-file output.',
      );
    }
    File(outputPath)
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(output);
  }

  /// Returns a JSON-serialisable summary of the SV synthesis.
  ///
  /// Contains the list of generated module definition names.
  @override
  Map<String, Object> toJson() => <String, Object>{
        'modules': [for (final fc in fileContents) fc.name],
      };
}
