// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: BSD-3-Clause
//
// system_verilog_service.dart
// Service wrapper for SystemVerilog synthesis.
//
// 2026 April 25
// Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

import 'dart:io';

import 'package:collection/collection.dart';
import 'package:rohd/rohd.dart';
import 'package:rohd/src/utilities/config.dart';
import 'package:rohd/src/utilities/timestamper.dart';

/// A service that wraps SystemVerilog synthesis of a [Module] hierarchy.
///
/// Provides access to the generated SV file contents and per-module
/// synthesis results, and optionally registers with [ModuleServices]
/// for DevTools inspection.
///
/// Example:
/// ```dart
/// final dut = MyModule(...);
/// await dut.build();
/// final sv = SystemVerilogService(dut);
///
/// // Write individual .sv files:
/// sv.writeFiles('build/');
///
/// // Or get the concatenated output (like generateSynth):
/// print(sv.allContents);
/// ```
class SystemVerilogService extends CodeGenService {
  /// The separator inserted between module definitions in the
  /// concatenated single-file output from [allContents].
  ///
  /// Matches the format historically produced by `Module.generateSynth()`.
  static const moduleSeparator = '\n\n////////////////////\n\n';

  /// The most recently registered [SystemVerilogService], or `null`.
  static SystemVerilogService? current;

  /// The top-level [Module] being synthesized.
  @override
  final Module module;

  /// The default location written by [write].
  ///
  /// A directory when [multiFile] is `true`, otherwise a single file path.
  @override
  final String? outputPath;

  /// Whether [write] emits one `.sv` file per module definition (`true`) or a
  /// single concatenated file (`false`).
  @override
  final bool multiFile;

  /// Configuration controlling generated SystemVerilog.
  final SystemVerilogSynthesizerConfiguration configuration;

  /// The underlying [SynthBuilder] that drove synthesis.
  late final SynthBuilder synthBuilder;

  /// The generated file contents (one per unique module definition).
  late final List<SynthFileContents> fileContents;

  /// Creates a [SystemVerilogService] for [module].
  ///
  /// [module] must already be built.
  ///
  /// If [outputPath] is provided, output is written immediately: a directory
  /// of per-module files when [multiFile] is `true`, otherwise the
  /// concatenated SV output (with header) to that single file.
  SystemVerilogService(this.module,
      {bool register = true,
      this.outputPath,
      this.multiFile = false,
      this.configuration = const SystemVerilogSynthesizerConfiguration()}) {
    if (!module.hasBuilt) {
      throw Exception(
        'Module must be built before creating SystemVerilogService. '
        'Call build() first.',
      );
    }

    synthBuilder = SynthBuilder(
        module, SystemVerilogSynthesizer(configuration: configuration));
    fileContents = synthBuilder.getSynthFileContents();

    if (outputPath != null) {
      write();
    }

    if (register) {
      current = this;
      ModuleServices.instance.register<SystemVerilogService>(this);
    }
  }

  /// All [SynthesisResult]s produced by synthesis.
  Set<SynthesisResult> get synthesisResults => synthBuilder.synthesisResults;

  /// Returns the concatenated SystemVerilog module definitions as a single
  /// string, without the generation header.
  ///
  /// For the full output with header (matching `Module.generateSynth()`),
  /// use [synthOutput].
  String get allContents =>
      fileContents.map((fc) => fc.contents).join(moduleSeparator);

  /// The ROHD generation header prepended to single-file output.
  String get synthHeader => '''
/**
 * Generated by ROHD - www.github.com/intel/rohd
 * Generation time: ${Timestamper.stamp()}
 * ROHD Version: ${Config.version}
 */

''';

  /// Returns the full single-file SystemVerilog output with header,
  /// identical to `Module.generateSynth()`.
  ///
  /// Computed once and cached so the timestamped header is stable for the
  /// lifetime of this service.
  late final String synthOutput = synthHeader + allContents;

  /// The combined single-file generated output (alias for [synthOutput]).
  @override
  String get output => synthOutput;

  /// Returns a map from module definition name to its SV file contents.
  ///
  /// Keys are [SynthesisResult.instanceTypeName] (the uniquified definition
  /// name used in the generated SV).
  Map<String, String> get contentsByName => {
        for (final fc in fileContents) fc.name: fc.contents,
      };

  /// Returns a map from module definition name
  /// ([Module.definitionName]) to its SV file contents.
  ///
  /// This uses the original definition name (not uniquified), matching
  /// the keys used by FLC trace data.
  @override
  Map<String, String> get contentsByDefinitionName {
    final result = <String, String>{};
    for (final sr in synthesisResults) {
      final defName = sr.module.definitionName;
      final instanceName = sr.instanceTypeName;
      // Find the file content matching this instance type name.
      final fc = fileContents.firstWhereOrNull((f) => f.name == instanceName);
      if (fc != null) {
        result[defName] = fc.contents;
      }
    }
    return result;
  }

  /// Writes each module's SV to a separate file in [directory].
  ///
  /// Files are named `<definitionName>.sv`.
  void writeFiles(String directory) {
    final dir = Directory(directory)..createSync(recursive: true);
    for (final fc in fileContents) {
      File('${dir.path}/${fc.name}.sv').writeAsStringSync(fc.contents);
    }
  }

  /// Writes the SV output to [path], or to [outputPath] when [path] is omitted.
  ///
  /// When [multiFile] is `true`, writes one `.sv` file per module definition
  /// into the target directory (see [writeFiles]); otherwise writes the
  /// concatenated [synthOutput] to the target file.
  @override
  void write([String? path]) {
    final target = path ?? outputPath;
    if (target == null) {
      throw ArgumentError(
        'No output path provided: pass a path to write() or set outputPath.',
      );
    }
    if (multiFile) {
      writeFiles(target);
    } else {
      File(target)
        ..parent.createSync(recursive: true)
        ..writeAsStringSync(synthOutput);
    }
  }

  /// Returns a JSON-serialisable summary of the SV synthesis.
  ///
  /// Contains the list of generated module definition names.
  @override
  Map<String, Object> toJson() => <String, Object>{
        'modules': [for (final fc in fileContents) fc.name],
      };
}
