#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-}"
overrides="pubspec_overrides.yaml"
widgets_overrides="packages/rohd_devtools_widgets/pubspec_overrides.yaml"
marker="# Generated by scripts/devtools_dev_mode.sh. Do not edit by hand."
rohd_path="${ROHD_LOCAL_PATH:-$(cd .. && pwd)}"
rohd_link=".rohd_local"

usage() {
  cat <<'USAGE'
Usage: scripts/devtools_dev_mode.sh <mode>

Modes:
  hr-he-hv  Hosted ROHD packages + hosted DevTools-extension packages + hosted viewers.
  lr-he-hv  Local ROHD packages + hosted DevTools-extension packages + hosted viewers.
  hr-le-hv  Hosted ROHD packages + local DevTools-extension packages + hosted viewers.
  lr-le-hv  Local ROHD packages + local DevTools-extension packages + hosted viewers.
  hr-he-lv  Hosted ROHD packages + hosted DevTools-extension packages + local viewers.
  lr-he-lv  Local ROHD packages + hosted DevTools-extension packages + local viewers.
  hr-le-lv  Hosted ROHD packages + local DevTools-extension packages + local viewers.
  lr-le-lv  Local ROHD packages + local DevTools-extension packages + local viewers.
  show   Print the current generated override file, if present.

Set ROHD_LOCAL_PATH to override the default local ROHD checkout, which is the
parent directory of rohd_devtools_extension in this workspace.

Local modes write paths through .rohd_local, a generated symlink to
ROHD_LOCAL_PATH. Retarget that symlink or rerun this script with ROHD_LOCAL_PATH
to switch local ROHD checkouts without editing every override path.
USAGE
}

ensure_managed_or_absent() {
  local overrides_file="$1"

  if [[ -f "$overrides_file" ]] && ! grep -qxF "$marker" "$overrides_file"; then
    echo "$overrides_file exists and was not generated by scripts/devtools_dev_mode.sh." >&2
    echo "Move or remove it before switching development modes." >&2
    exit 1
  fi
}

ensure_rohd_link() {
  if [[ -e "$rohd_link" && ! -L "$rohd_link" ]]; then
    echo "$rohd_link exists and is not a symlink." >&2
    echo "Move or remove it before switching local ROHD checkouts." >&2
    exit 1
  fi

  ln -sfn "$rohd_path" "$rohd_link"
}

write_overrides() {
  local local_rohd="$1"
  local local_extension="$2"
  local local_viewer="$3"

  ensure_managed_or_absent "$overrides"
  ensure_managed_or_absent "$widgets_overrides"

  if [[ "$local_rohd" == "no" && "$local_extension" == "no" && "$local_viewer" == "no" ]]; then
    rm -f "$overrides"
    rm -f "$widgets_overrides"
    echo "Removed $overrides and $widgets_overrides; using hosted dependencies from pubspec.yaml."
    return
  fi

  ensure_rohd_link

  cat > "$overrides" <<YAML
$marker
# This file is intentionally ignored by git.
dependency_overrides:
YAML

  if [[ "$local_rohd" == "yes" ]]; then
    cat >> "$overrides" <<'YAML'
  rohd:
    path: .rohd_local
  rohd_hcl:
    path: ../../../rohd-hcl
  rohd_hierarchy:
    path: .rohd_local/packages/rohd_hierarchy
YAML
  fi

  if [[ "$local_extension" == "yes" ]]; then
    cat >> "$overrides" <<'YAML'
  rohd_devtools_widgets:
    path: packages/rohd_devtools_widgets
  rohd_source_navigator:
    path: .rohd_local/rohd_extension/dart
YAML
  fi

  if [[ "$local_viewer" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  dart_wellen:
    path: ${RELEASE_DIR:-$HOME/release}/rohd-wave-viewer/packages/dart_wellen
  rohd_schematic_viewer:
    path: ${RELEASE_DIR:-$HOME/release}/rohd-schematic-viewer
  rohd_wave_viewer:
    path: ${RELEASE_DIR:-$HOME/release}/rohd-wave-viewer
  rohd_waveform:
    path: ${RELEASE_DIR:-$HOME/release}/rohd-wave-viewer/packages/rohd_waveform
YAML
  fi

  if [[ "$local_rohd" == "yes" ]]; then
    cat > "$widgets_overrides" <<'YAML'
# Generated by scripts/devtools_dev_mode.sh. Do not edit by hand.
# This file is intentionally ignored by git.
dependency_overrides:
  rohd:
    path: ../../..
  rohd_hcl:
    path: ../../../../../rohd-hcl
YAML
  else
    rm -f "$widgets_overrides"
  fi

  echo "Wrote $overrides for $mode mode."
}

case "$mode" in
  hr-he-hv)
    write_overrides no no no
    ;;
  lr-he-hv)
    write_overrides yes no no
    ;;
  hr-le-hv)
    write_overrides no yes no
    ;;
  lr-le-hv)
    write_overrides yes yes no
    ;;
  hr-he-lv)
    write_overrides no no yes
    ;;
  lr-he-lv)
    write_overrides yes no yes
    ;;
  hr-le-lv)
    write_overrides no yes yes
    ;;
  lr-le-lv)
    write_overrides yes yes yes
    ;;
  show)
    if [[ -f "$overrides" ]]; then
      cat "$overrides"
    else
      echo "No $overrides present; using hosted dependencies from pubspec.yaml."
    fi
    ;;
  -h|--help|help|"")
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac